version: '3.4'
services:
  server:
    image: python:3.9.10
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      PYTHONPATH: $PYTHONPATH:src
      PYTHONUSERBASE: /mnt/vendor
      IMPORT_PATH: /mnt/test/fixture
    command: python src/server.py

  db:
    image: postgres:12.4
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./.docker/psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
